### ISSUE TITLE
Debugging virtual platform with gdb

### ISSUE THREAD

**Issue by boiihong** [nvdla/vp#11]
Hello all,
I am trying to debug NVDLA virtual platform using gdb.
I have no idea how to debug this running process.
It is even harder because i have to debug QEMU process (aarch64_toplevel) to see NVDLA working..

Is there any clever way to see how NVDLA working in a step-by-step fashion?
Please give me some advice then i'll do the work and post the result in here.
![qemu](https://user-images.githubusercontent.com/22439118/41202663-7907a06c-6d07-11e8-9bdb-fd766a7ea142.png)
Thanks!

**Comment by HaiqingSun** [comment]
Hi boiihong,

You want to see how NVDLA cmodel work step by step with source code? 
Currently DLA cmod code does not include debug version, so if you want to see the source code in gdb, you need to do some hack in Makefile
https://github.com/nvdla/hw/blob/nvdlav1/cmod/Makefile 
CPPFLAGS ?= $(INC_FLAGS) -MMD -MP **-g** -fPIC -Wall -Werror -DSC_INCLUDE_DYNAMIC_PROCESSES -Wp,-w -std=c++11

After the hack, you need to re-compile the HW and VP code.
Now you can set the breakpoint inside the DLA cmod code, such as b NvdlaAxiAdaptor.cpp:60

When SW test begin, gdb will stop with breakpoint.
![image](https://user-images.githubusercontent.com/30793988/41269652-f82ff61e-6e38-11e8-95b8-e37ec64258e0.png)

Now, you can check the DLA behavior by next command

Best Regards,
Haiqing

**Comment by boiihong** [comment]
Many thanks for your advice, HaiqingSun. 
I'll try that.

Best Regards,
boiihong

**Comment by boiihong** [comment]
Hi HaiqingSun.
I success.
![default](https://user-images.githubusercontent.com/22439118/41284036-2b41ccd2-6e73-11e8-8c19-4c2eee6a49ec.png)

Amazing, 
Thank you

**Comment by Abraham-Xu** [comment]
> Hi boiihong,
> 
> You want to see how NVDLA cmodel work step by step with source code?
> Currently DLA cmod code does not include debug version, so if you want to see the source code in gdb, you need to do some hack in Makefile
> https://github.com/nvdla/hw/blob/nvdlav1/cmod/Makefile
> CPPFLAGS ?= $(INC_FLAGS) -MMD -MP **-g** -fPIC -Wall -Werror -DSC_INCLUDE_DYNAMIC_PROCESSES -Wp,-w -std=c++11
> 
> After the hack, you need to re-compile the HW and VP code.
> Now you can set the breakpoint inside the DLA cmod code, such as b NvdlaAxiAdaptor.cpp:60
> 
> When SW test begin, gdb will stop with breakpoint.
> ![image](https://user-images.githubusercontent.com/30793988/41269652-f82ff61e-6e38-11e8-95b8-e37ec64258e0.png)
> 
> Now, you can check the DLA behavior by next command
> 
> Best Regards,
> Haiqing

Hi, Haiqing,
When I try this method, the problem I encountered is that the program can only stop before entering vp but not in vp. Is there any solution to stop at the breakpoints in cmod when vp runing? This problem puzzled me for a long time. Thank you very much!

**Comment by linbaiwpi** [comment]
Hi @HaiqingSun and @boiihong,
I followed what you mentioned above, but still cannot set break points in source code. Could you help me figure out what the problem is? Below I write down what I have done in detail. BTW, I am using docker (privileged mode) supplied by vp repository.

1) Hack the Makefile in nvdla/hw/cmod
CPPFLAGS ?= $(INC_FLAGS) -MMD -MP **-g** -fPIC -Wall -Werror -DSC_INCLUDE_DYNAMIC_PROCESSES -Wp,-w -std=c++11
And recompile the hw using command
`./tools/bin/tmake -build cmod_top`
2) Recompile the vp using the following commands
`cmake -DCMAKE_INSTALL_PREFIX=build -DSYSTEMC_PREFIX=/usr/local/systemc-2.3.0/ -DNVDLA_HW_PREFIX=/vp/hw/ -DNVDLA_HW_PROJECT=nv_full -DCMAKE_BUILD_TYPE=Debug`
`make`
`make install`
3) Run the virtual simulator
`./build/bin/aarch64_toplevel -c conf/aarch64_nvdla.lua`
4) Run GDB in another terminal
`ps -ef | grep "aarch64_toplevel"`
`gdb attach <PID>`

I pasted the terminal print:
![Screenshot from 2022-01-03 10-39-56](https://user-images.githubusercontent.com/31357378/147967928-85cd14fd-8f3c-422f-a842-58b87b0cd77d.png)

BR,
Lin

P.S. someone else mentioned I have to add a CPU extra argument "-s" in aarch64_nvdla.lua. But this does not help in my case.
