### ISSUE TITLE
How to copy files from local path into virtual platform

### ISSUE THREAD

**Issue by redglass1984** [nvdla/vp#18]
Hi,

I have run docker VP version on my Ubuntu16.04 compluter, and enter VP already.
I can run runtime inside VP.

But I don't know how to copy my loadable and test data from my local disk into VP.
Do you have any recomand on how to do this.

Thanks!

**Comment by JunningWu** [comment]
Using mount
        
            
                
                    
                            
                                
                            
                            
                                Junning Wu
                            
                    
                        
                            
                                    邮箱：wujunning11@gmail.com
                            
                        
                
            
        Signature is customized by Netease Mail Master
On 07/06/2018 16:04, redglass1984 wrote: Hi,
I have run docker VP version on my Ubuntu16.04 compluter, and enter VP already.
I can run runtime inside VP.
But I don't know how to copy my loadable and test data from my local disk into VP.
Do you have any recomand on how to do this.
Thanks!

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/nvdla/vp","title":"nvdla/vp","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/nvdla/vp"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"How to copy files from local path into virtual platform (#18)"}],"action":{"name":"View Issue","url":"https://github.com/nvdla/vp/issues/18"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/nvdla/vp/issues/18",
"url": "https://github.com/nvdla/vp/issues/18",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "How to copy files from local path into virtual platform (#18)",
"sections": [
{
"text": "",
"activityTitle": "**redglass1984**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@redglass1984",
"facts": [
{
"name": "Repository: ",
"value": "nvdla/vp"
},
{
"name": "Issue #: ",
"value": 18
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"nvdla/vp\",\n\"issueId\": 18,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"nvdla/vp\",\n\"issueId\": 18\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/nvdla/vp/issues/18"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 353644872\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by redglass1984** [comment]
Can you help to share me a more detail example.
Like how to mount /home/folder to VP.

Thanks a lot
